=== Saransh-Sharma/test-framework-and-suites-for-android/acs/acs/_Catalogs/UseCase/usecase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="types.xsd"/>

    <xs:element name="UseCases">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="UseCase"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UseCase">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ClassName"/>
                <xs:element ref="Description"/>
                <xs:element ref="Environment"/>
                <xs:element minOccurs="0" ref="Parameters"/>
            </xs:sequence>
            <xs:attribute name="Id" use="required" type="xs:NCName"/>
            <xs:attribute name="Domain" use="required" type="domains"/>
            <xs:attribute name="SubDomain" use="required" type="subdomains"/>
            <xs:attribute name="OS" use="required" type="os"/>
            <xs:attribute name="Status" use="required" type="status"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ClassName" type="classname"/>
    <xs:element name="Description" type="description"/>
    <xs:element name="Capabilities" type="xs:NCName"/>
    <xs:element name="PossibleValues" type="mixed"/>
    <xs:element name="DefaultValue" type="xs:string"/>
    <xs:element name="Blank" type="mixed"/>

    <xs:element name="Environment">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Dependency"/>
                <xs:element ref="Capabilities"/>
            </xs:choice>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Parameters">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Parameter">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Description"/>
                <xs:element ref="PossibleValues"/>
                <xs:element ref="DefaultValue"/>
                <xs:element ref="Blank"/>
                <xs:element minOccurs="0" ref="Dependencies"/>
            </xs:sequence>
            <xs:attribute name="isOptional" use="required" type="xs:boolean"/>
            <xs:attribute name="name" use="required" type="xs:token"/>
            <xs:attribute name="type" use="required" type="xs:token"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Dependencies">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Dependency"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Dependency">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="isOptional" type="xs:boolean"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs_test_scripts/_Catalogs/UseCase/MISC/PY_UNIT.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<UseCases xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../acs/acs/_Catalogs/UseCase/usecase.xsd">
    <UseCase Id="PY_UNIT" Domain="MISC" SubDomain="EXEC" OS="ANDROID" Status="DONE">
        <ClassName>UseCase.Misc.PY_UNIT.PyUnit</ClassName>
        <Description>Use case for running existing test cases target to be run via noserunner</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="TEST_DATA_ROOT" type="STRING" isOptional="false">
                <Description>Config root for py unit</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
            <Parameter name="TEST_CASE" type="STRING" isOptional="false">
                <Description>test case name (format should be 'module.class.method')</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
        </Parameters>
    </UseCase>
</UseCases>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs/acs/_Catalogs/UseCase/MISC/EXEC.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<UseCases xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../usecase.xsd">
    <UseCase Id="EXEC_SCRIPT" Domain="MISC" SubDomain="EXEC" OS="ANDROID" Status="DONE">
        <ClassName>acs.UseCase.Misc.EXEC_SCRIPT.ExecScript</ClassName>
        <Description>Open implementation script taking python scripts as inputs.</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="SETUP_SCRIPT_PATH" type="SCRIPT" isOptional="true">
                <Description>Script to set up the test - python script, (e.g. exec_script_setup.py)</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
            <Parameter name="SCRIPT_PATH" type="SCRIPT" isOptional="false">
                <Description>Script to run the test - python script, (e.g. scripts/check_screen_on.py)</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
            <Parameter name="TEAR_DOWN_SCRIPT_PATH" type="SCRIPT" isOptional="true">
                <Description>Script to clean the test - python script, (e.g. exec_script_tear_down.py)</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
            <Parameter name="FINALIZE_SCRIPT_PATH" type="FINALIZE_SCRIPT" isOptional="true">
                <Description>Script to finalize the test - python script, (e.g. exec_script_finalize.py)</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
            <Parameter name="ANY_VALUE" type="STRING" isOptional="true">
                <Description>User customized parameter for script execution. Can have any name with any value (e.g. PKP
                    DURATION, DATA_CODING_SCHEME, SCREEN_SHOT_REF, DISABLE_NFC)
                </Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
        </Parameters>
    </UseCase>
    <UseCase Id="EXEC" Domain="MISC" SubDomain="EXEC" OS="N/A" Status="DONE">
        <ClassName>acs.UseCase.Misc.EXEC.Exec</ClassName>
        <Description>General execution use case. Run cmd one after the other</Description>
        <Environment name="ANY"/>
        <!--
        This use case will export all ACS Global parameters as an JSON object into ACS_GLOBAL_PARAMETERS
        environment variable so that user can access them from inside the script that is being executed
        -->
        <Parameters>
            <Parameter name="SETUP_CMD" type="STRING" isOptional="true">
                <Description>Action or sequence of actions (SETUP_CMD, SETUP_CMD1, SETUP_CMD2, ...)</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
            <Parameter name="SETUP_TIMEOUT" type="FLOAT" isOptional="true">
                <Description>Timeout is seconds for the setup cmd [mandatory if SETUP_CMD defined]</Description>
                <PossibleValues/>
                <DefaultValue>1</DefaultValue>
                <Blank/>
            </Parameter>
            <Parameter name="SETUP_EXPECT_RESULT" type="STRING" isOptional="true">
                <Description>Expected result int (exec return code) or string (that will be search in the stdout)
                    If you need to check device log, add [TRIG_LOG] message to trigger as valueExpected
                    result (return code or pattern) [optional, default value is 0]
                </Description>
                <PossibleValues/>
                <DefaultValue>0</DefaultValue>
                <Blank/>
            </Parameter>
            <Parameter name="RUN_CMD" type="STRING" isOptional="false">
                <Description>Action or sequence of actions (SETUP_CMD, SETUP_CMD1, SETUP_CMD2, ...)</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
            <Parameter name="RUN_TIMEOUT" type="FLOAT" isOptional="true">
                <Description>Timeout is seconds for the run cmd</Description>
                <PossibleValues/>
                <DefaultValue>1</DefaultValue>
                <Blank/>
            </Parameter>
            <Parameter name="RUN_EXPECT_RESULT" type="STRING" isOptional="true">
                <Description>Expected result int (exec return code) or string (that will be search in the stdout)
                    If you need to check device log, add [TRIG_LOG] message to trigger as
                    value (optional, default value = 0)
                </Description>
                <PossibleValues/>
                <DefaultValue>0</DefaultValue>
                <Blank/>
            </Parameter>
            <Parameter name="TEAR_DOWN_CMD" type="STRING" isOptional="true">
                <Description>Action or sequence of actions (SETUP_CMD, SETUP_CMD1, SETUP_CMD2, ...)</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank/>
            </Parameter>
            <Parameter name="TEAR_DOWN_TIMEOUT" type="FLOAT" isOptional="true">
                <Description>Timeout of the teardown cmd [mandatory if TEAR_DOWN_CMD defined]</Description>
                <PossibleValues/>
                <DefaultValue>1</DefaultValue>
                <Blank/>
            </Parameter>
            <Parameter name="TEAR_DOWN_EXPECT_RESULT" type="STRING" isOptional="true">
                <Description>Expected result int (exec return code) or string (that will be search in the stdout)
                    If you need to check device log, add [TRIG_LOG] message to trigger as
                    value (optional, default value = 0)
                </Description>
                <PossibleValues/>
                <DefaultValue>0</DefaultValue>
                <Blank/>
            </Parameter>
        </Parameters>
    </UseCase>
</UseCases>
