=== Saransh-Sharma/test-framework-and-suites-for-android/acs/acs/_Catalogs/Device/Capabilities/DeviceCapabilities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="capability.xsd"/>
    <xs:element name="DeviceCapabilities">
        <xs:complexType>
            <xs:sequence>
                    <xs:element name="Capability" type="capability" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs_test_suites/_Catalogs/Device/Capabilities/wearable.xml
<DeviceCapabilities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="../../../../acs/acs/_Catalogs/Device/Capabilities/DeviceCapabilities.xsd">
    <Capability>touchscreen</Capability>
    <Capability>gps</Capability>
    <Capability>bluetooth</Capability>
    <Capability>vibrator</Capability>
    <Capability>usb_charging</Capability>
    <Capability>wireless_charging</Capability>
    <Capability>modem</Capability>
</DeviceCapabilities>
