=== Saransh-Sharma/test-framework-and-suites-for-android/acs/acs/_Catalogs/TestStep/teststep.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:include schemaLocation="types.xsd"/>

    <xs:element name="TestSteps">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="TestStep"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="TestStep">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="ClassName"/>
            <xs:element ref="Description"/>
            <xs:element ref="Environment"/>
            <xs:element ref="Parameters"/>
          </xs:sequence>
          <xs:attribute name="Id" use="required" type="xs:NCName"/>
          <xs:attribute name="Domain" use="required" type="domains"/>
          <xs:attribute name="SubDomain" use="required" type="subdomains"/>
          <xs:attribute name="Feature" use="required" type="features"/>
          <xs:attribute name="Status" use="required" type="status"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ClassName" type="classname"/>
    <xs:element name="Description" type="description"/>
    <xs:element name="Capabilities" type="xs:NCName"/>
    <xs:element name="PossibleValues" type="mixed"/>
    <xs:element name="DefaultValue" type="mixed"/>
    <xs:element name="Blank" type="mixed"/>

    <xs:element name="Parameter">
        <xs:complexType>
          <xs:sequence>
              <xs:element name="Description">
                  <xs:complexType mixed="true">
                      <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Key"/>
                      </xs:sequence>
                  </xs:complexType>
              </xs:element>
              <xs:element ref="PossibleValues"/>
            <xs:element ref="DefaultValue"/>
            <xs:element ref="Blank"  minOccurs="0"/>
          </xs:sequence>
          <xs:attribute name="name" use="required" type="xs:NCName"/>
          <xs:attribute name="type" use="required" type="xs:NCName"/>
          <xs:attribute name="isOptional" use="required" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Parameters">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Environment">
        <xs:complexType mixed="true">
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="Dependency"/>
            <xs:element ref="Capabilities"/>
          </xs:choice>
          <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Dependencies">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" ref="Dependency"/>
          </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Dependency">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:NCName">
              <xs:attribute name="isOptional" type="xs:boolean"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="Key">
        <xs:complexType mixed="true">
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="type" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs_test_scripts/_Catalogs/TestStep/Utilities/BENCH_CONFIG.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<TestSteps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../acs/acs/_Catalogs/TestStep/teststep.xsd">
    <TestStep Id="GET_EQT_CONFIG" Domain="UTILITIES" SubDomain="BENCH_CONFIG" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.BenchConfig.GetEqtConfig.GetEqtConfig</ClassName>
        <Description>Save equipment config in a context variable</Description>
        <Environment name="ANY">
        </Environment>
        <Parameters>
            <Parameter name="EQT" type="STRING" isOptional="false">
                <Description>The equipment name shall refer to an existing equipment of the Bench config.</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
            <Parameter name="SAVE_AS" type="CONTEXT" isOptional="false">
                <Description>
                    <Key name="KEY_NAME_DEFINED_BY_USER" type="STRING">Name of the context variable where the equipment config will be saved.</Key>
                </Description>
                <PossibleValues />
                <DefaultValue />
            </Parameter>
        </Parameters>
    </TestStep>
</TestSteps>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs_test_scripts/_Catalogs/TestStep/Utilities/LOCAL_TASKS.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<TestSteps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../acs/acs/_Catalogs/TestStep/teststep.xsd">
    <TestStep Id="RUN_LOCAL_CMD" Domain="UTILITIES" SubDomain="LOCAL_TASKS" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.LocalTasks.RunLocalCommand.RunLocalCommand</ClassName>
        <Description>Execute a command on the local computer</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="TIMEOUT" type="INTEGER" isOptional="false">
                <Description>Timeout (in seconds) to apply to the command execution</Description>
                <PossibleValues/>
                <DefaultValue>5</DefaultValue>
            </Parameter>
            <Parameter name="COMMAND" type="STRING" isOptional="false">
                <Description>Command to execute on the device</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
            <Parameter name="SILENT_MODE" type="BOOLEAN" isOptional="false">
                <Description>Whether ACS log is to be hidden at execution</Description>
                <PossibleValues/>
                <DefaultValue>False</DefaultValue>
            </Parameter>
            <Parameter name="SAVE_AS" type="CONTEXT" isOptional="false">
                <Description>
                    <Key name="COMMAND_RESULT" type="STRING">Name of the context variable which will store the content
                        of the standard output of the command.</Key>
                </Description>
                <PossibleValues />
                <DefaultValue />
            </Parameter>
        </Parameters>
    </TestStep>
</TestSteps>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs_test_scripts/_Catalogs/TestStep/Utilities/CHECKS.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<TestSteps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../acs/acs/_Catalogs/TestStep/teststep.xsd">
    <TestStep Id="COMPARE" Domain="UTILITIES" SubDomain="CHECKS" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.Checks.Compare.Compare</ClassName>
        <Description>Compare two given arguments using the given comparison operator</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="FIRST" type="STRING" isOptional="false">
                <Description>First value to compare</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
            <Parameter name="SECOND" type="STRING" isOptional="false">
                <Description>Second value to compare. can be a blank string</Description>
                <PossibleValues/>
                <DefaultValue/>
                <Blank>True</Blank>
            </Parameter>
            <Parameter name="OPERATOR" type="STRING" isOptional="false">
                <Description>
                Comparison operator.  WITHIN_BOUNDS:  SECOND must be of the form x,d where x is the target value and d is the acceptable delta from x.
                In other words, it looks at whether FIRST is within the range [x-d, x+d].  Example:  FIRST="8", SECOND="10,3", OPERATOR="WITHIN_BOUNDS, PASS_IF="True".
                Result is PASS since 8 is within the range [7,13].
                </Description>
                <PossibleValues>EQUAL;NOT_EQUAL;GREATER;LESS;GREATER_OR_EQUAL;LESS_OR_EQUAL;IN;WITHIN_BOUNDS</PossibleValues>
                <DefaultValue/>
            </Parameter>
            <Parameter name="PASS_IF" type="BOOLEAN" isOptional="false">
                <Description>
                    Defines whether the test must pass when the comparison succeeds, or fails. In this way it's possible
                    to make flexible comparisons. so if FIRST=10 and SECOND=10 and operator is equal, by default the test
                    will pass. If pass_if is false, then the test will fail.
                </Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
        </Parameters>
    </TestStep>
    <TestStep Id="CHECK_CONTEXT_INFO" Domain="UTILITIES" SubDomain="CHECKS" Feature="" Status="DONE">
            <ClassName>acs_test_scripts.TestStep.Utilities.Checks.CheckContextInfoExists.CheckContextInfoExists</ClassName>
            <Description>Check if a key is in the context</Description>
            <Environment name="ANY"/>
            <Parameters>
                <Parameter name="KEY" type="STRING" isOptional="false">
                    <Description>Key to search in the context</Description>
                    <PossibleValues/>
                    <DefaultValue/>
                </Parameter>
            </Parameters>
    </TestStep>
    <TestStep Id="CHECK_CAMPAIGN_INFO" Domain="UTILITIES" SubDomain="CHECKS" Feature="" Status="DONE">
            <ClassName>acs_test_scripts.TestStep.Utilities.Checks.CheckCampaignInfo.CheckCampaignInfo</ClassName>
            <Description>Check if a KEY was in the campaign configuration file and store the value found into PARAM_VALUE as a string.
                            Use DEFAULT_VALUE for PARAM_VALUE if KEY was not found in the configuration file.</Description>
            <Environment name="ANY"/>
            <Parameters>
                <Parameter name="KEY" type="STRING" isOptional="false">
                    <Description>Value to search for in the configuration file.</Description>
                    <PossibleValues/>
                    <DefaultValue/>
                </Parameter>
                <Parameter name="PARAM_VALUE" type="CONTEXT" isOptional="false">
                    <Description>
                        <Key name="PARAM_VALUE_KEY" type="STRING">Final parameter value, either from DEFAULT_VALUE or from Campaign config.</Key>
                    </Description>
                    <PossibleValues/>
                    <DefaultValue/>
                </Parameter>
                <Parameter name="DEFAULT_VALUE" type="STRING" isOptional="false">
                    <Description>Value to store in PARAM_VALUE if nothing was found for KEY in the configuration file.</Description>
                    <PossibleValues/>
                    <DefaultValue/>
                </Parameter>
            </Parameters>
    </TestStep>
    <TestStep Id="CHECK_PATH" Domain="UTILITIES" SubDomain="CHECKS" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.Checks.CheckPath.CheckPath</ClassName>
        <Description>Check some properties for the given path on host machine (existence, representing a file, ...)</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="PATH_TO_CHECK" type="STRING" isOptional="false">
                <Description>Path to check</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
            <Parameter name="OPERATOR" type="STRING" isOptional="false">
                <Description>Operation to do on the path</Description>
                <PossibleValues>EXIST;IS_FILE;IS_DIRECTORY</PossibleValues>
                <DefaultValue/>
            </Parameter>
            <Parameter name="PASS_IF" type="BOOLEAN" isOptional="false">
                <Description>
                    Defines whether the test must pass when the comparison succeeds, or fails. In this way it's possible
                    to make flexible comparisons.
                </Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
        </Parameters>
    </TestStep>
    <TestStep Id="CHECK_SNIFFER_LOG" Domain="UTILITIES" SubDomain="CHECKS" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Equipment.Sniffer.CheckSnifferLog.CheckSnifferLog</ClassName>
        <Description>Check if expected requests exists in sniffer log.</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="SNIFFER_LOG_FILE" type="STRING" isOptional="false">
                <Description>Path and name of the sniffer log to analyze.</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
            <Parameter name="FRAME_TO_CHECK" type="STRING" isOptional="false">
                <Description>Frame to check. Can be a beacon frame or an association request frame.</Description>
                <PossibleValues>CHECK_FRAME_BEACON;CHECK_FRAME_ASSOCIATION_REQUEST</PossibleValues>
                <DefaultValue/>
            </Parameter>
            <Parameter name="PARAM_TO_CHECK" type="STRING" isOptional="false">
                <Description>Parameter in the frame to check.</Description>
                <PossibleValues>CHECK_BANDWIDTH;CHECK_CAPABILITIES</PossibleValues>
                <DefaultValue/>
            </Parameter>
            <Parameter name="PARAM_VALUE" type="STRING" isOptional="false">
                <Description>Value of the parameter to check. Can be a capability or a bandwidth</Description>
                <PossibleValues>20MHZ;40MHZ;80MHZ;HT_CAPABILITIES;VHT_CAPABILITIES</PossibleValues>
                <DefaultValue/>
            </Parameter>
            <Parameter name="MAC_ADDR_SOURCE" type="STRING" isOptional="true">
                <Description>WiFi MAC address of the device which sent the frame.</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
            <Parameter name="MAC_ADDR_RECEIVER" type="STRING" isOptional="true">
                <Description>WiFi MAC address of the device which received the frame.</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
        </Parameters>
    </TestStep>
    <TestStep Id="PRINT_VALUE" Domain="UTILITIES" SubDomain="CHECKS" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.Checks.PrintValue.PrintValue</ClassName>
        <Description>Prints a given variable value for debugging purposes.</Description>
        <Environment name="ANY" />
        <Parameters>
            <Parameter name="VALUE_TO_PRINT" type="STRING" isOptional="false">
                <Description>Variable you want to print the value of.</Description>
                <PossibleValues />
                <DefaultValue />
            </Parameter>
        </Parameters>
    </TestStep>
    <TestStep Id="PRINT_MSG" Domain="UTILITIES" SubDomain="CHECKS" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.Checks.PrintMsg.PrintMsg</ClassName>
        <Description>Prints a message for debugging purposes.</Description>
        <Environment name="ANY" />
        <Parameters>
            <Parameter name="MSG_TO_PRINT" type="STRING" isOptional="false">
                <Description>Message to print.</Description>
                <PossibleValues />
                <DefaultValue />
            </Parameter>
        </Parameters>
    </TestStep>
</TestSteps>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs_test_scripts/_Catalogs/TestStep/Utilities/TIMINGS.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<TestSteps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../acs/acs/_Catalogs/TestStep/teststep.xsd">
    <TestStep Id="SUSPEND" Domain="UTILITIES" SubDomain="TIMINGS" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.Timings.Suspend.Suspend</ClassName>
        <Description>Suspend execution for x (float) seconds</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="DURATION_IN_SEC" type="FLOAT" isOptional="false">
                <Description>Time to wait in seconds</Description>
                <PossibleValues>[0.0:86400.0]</PossibleValues>
                <DefaultValue>1.0</DefaultValue>
            </Parameter>
            <Parameter name="REFRESH_STDOUT_IN_SEC" type="FLOAT" isOptional="true">
                <Description>Update stdout every x seconds</Description>
                <PossibleValues>[0.0:86400.0]</PossibleValues>
                <DefaultValue>300.0</DefaultValue>
            </Parameter>
        </Parameters>
    </TestStep>
    <TestStep Id="SUSPEND_TO_TIME" Domain="UTILITIES" SubDomain="TIMINGS" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.Timings.SuspendToTime.SuspendToTime</ClassName>
        <Description>Suspend execution until specified time is reached</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="TO_TIME" type="FLOAT" isOptional="false">
                <Description>Timestamp to wait in seconds</Description>
                <PossibleValues></PossibleValues>
                <DefaultValue></DefaultValue>
            </Parameter>
        </Parameters>
    </TestStep>
</TestSteps>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs_test_scripts/_Catalogs/TestStep/Utilities/FRAMEWORK.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<TestSteps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../acs/acs/_Catalogs/TestStep/teststep.xsd">
    <TestStep Id="STORE_STRING_IN_CTX" Domain="UTILITIES" SubDomain="FRAMEWORK" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.Framework.StoreStringInContext.StoreStringInContext</ClassName>
        <Description>Add input string into context</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="INPUT" type="STRING" isOptional="false">
                <Description>String to add into context</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
            <Parameter name="OUTPUT" type="CONTEXT" isOptional="false">
                <Description>
                    <Key name="STORED_STRING" type="STRING">String copied from INPUT</Key>
                </Description>
                <PossibleValues />
                <DefaultValue />
            </Parameter>
        </Parameters>
    </TestStep>
    <TestStep Id="EXEC_SCRIPT" Domain="UTILITIES" SubDomain="FRAMEWORK" Feature="" Status="DONE">
        <ClassName>acs_test_scripts.TestStep.Utilities.Framework.ExecScript.ExecScript</ClassName>
        <Description>Execute an external python script</Description>
        <Environment name="ANY"/>
        <Parameters>
            <Parameter name="SCRIPT_PATH" type="STRING" isOptional="false">
                <Description>Script's path, absolute, or relative to ExecutionConfig folder,
                    or relative to test case's folder</Description>
                <PossibleValues/>
                <DefaultValue/>
            </Parameter>
        </Parameters>
    </TestStep>
</TestSteps>
