=== Saransh-Sharma/test-framework-and-suites-for-android/acs/acs/_Catalogs/Parameter/parameter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--This File is the XML Schema for the Parameter xml file-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Parameter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Parameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Description"/>
        <xs:element ref="Domain"/>
        <xs:element ref="Type"/>
        <xs:element ref="PossibleValues"/>
        <xs:element ref="DefaultValue"/>
        <xs:element ref="Blank"/>
        <xs:element minOccurs="0" ref="Dependencies"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Description" type="xs:string"/>
  <xs:element name="Domain" type="xs:NCName"/>
  <xs:element name="Type" type="xs:NCName"/>
  <xs:element name="PossibleValues">
    <xs:complexType mixed="true">
      <xs:attribute name="override" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DefaultValue">
    <xs:complexType mixed="true">
      <xs:attribute name="override" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Blank">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:boolean">
          <xs:attribute name="override" use="required" type="xs:boolean"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Dependencies">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Dependency"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Dependency">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="DependencyParameter"/>
      </xs:sequence>
      <xs:attribute name="description" use="required"/>
      <xs:attribute name="mandatory" use="required" type="xs:boolean"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DependencyParameter">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="possibleValue" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Saransh-Sharma/test-framework-and-suites-for-android/acs_test_scripts/_Catalogs/Parameter/common.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Common Parameters Catalog Template : new template to automatically populate i-TAP database with Common TC params -->
<Parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../acs/src/_Catalogs/Parameter/parameter.xsd">
    <Parameter name="FLOAT">
        <Description>Simple float</Description>
        <Domain>COMMON</Domain>
        <Type>float</Type>
        <PossibleValues override="true"/>
        <DefaultValue override="true">1.0</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="INTEGER">
        <Description>Simple integer</Description>
        <Domain>COMMON</Domain>
        <Type>int</Type>
        <PossibleValues override="true"/>
        <DefaultValue override="true">1</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="STRING">
        <Description>Simple character string</Description>
        <Domain>COMMON</Domain>
        <Type>str</Type>
        <PossibleValues override="true"/>
        <DefaultValue override="true"/>
        <Blank override="true">false</Blank>
    </Parameter>
    <Parameter name="BOOLEAN">
        <Description>Simple boolean</Description>
        <Domain>COMMON</Domain>
        <Type>bool</Type>
        <PossibleValues override="false">true;false</PossibleValues>
        <DefaultValue override="true">false</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="SCRIPT">
        <Description>Script to run</Description>
        <Domain>COMMON</Domain>
        <Type>scriptfile</Type>
        <PossibleValues override="false"/>
        <DefaultValue override="false"/>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="CONTEXT">
        <Description>String representing key name of a single piece of information to be saved into a context
        </Description>
        <Domain>COMMON</Domain>
        <Type>str</Type>
        <PossibleValues override="true"/>
        <DefaultValue override="true"/>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="LIST">
        <Description>String representing a list of values separated by '[|]'
        </Description>
        <Domain>COMMON</Domain>
        <Type>list</Type>
        <PossibleValues override="true"/>
        <DefaultValue override="true"/>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="VOLUME_IN_PERCENT">
        <Description>Volume value in percent from 0 to 100</Description>
        <Domain>COMMON</Domain>
        <Type>int</Type>
        <PossibleValues override="false">[0:100]</PossibleValues>
        <DefaultValue override="true">10</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="DURATION_IN_MSEC">
        <Description>Duration in milliseconds</Description>
        <Domain>COMMON</Domain>
        <Type>int</Type>
        <PossibleValues override="true">[0:1000000]</PossibleValues>
        <DefaultValue override="true">300000</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="DURATION_IN_SEC">
        <Description>Duration in seconds</Description>
        <Domain>COMMON</Domain>
        <Type>int</Type>
        <PossibleValues override="true">[0:100000]</PossibleValues>
        <DefaultValue override="true">300</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="TIMEOUT_IN_SEC">
        <Description>Timeout in seconds</Description>
        <Domain>COMMON</Domain>
        <Type>int</Type>
        <PossibleValues override="true">[0:200000]</PossibleValues>
        <DefaultValue override="true">10</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="TIMEOUT_IN_MSEC">
        <Description>Timeout in milliseconds</Description>
        <Domain>COMMON</Domain>
        <Type>int</Type>
        <PossibleValues override="true">[0:200000]</PossibleValues>
        <DefaultValue override="true">10000</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="AUDIO_OUTPUT">
        <Description>The device used for audio output, could be speaker, headset or none</Description>
        <Domain>COMMON</Domain>
        <Type>str</Type>
        <PossibleValues override="false">speaker;headset;none</PossibleValues>
        <DefaultValue override="true">none</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="XFER_DIRECTION">
        <Description>Transfer direction</Description>
        <Domain>COMMON</Domain>
        <Type>str</Type>
        <PossibleValues override="false">UL;DL;BOTH</PossibleValues>
        <DefaultValue override="true">UL</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="IS_FLIGHT_MODE_ENABLED">
        <Description>Enabled/Disabled Flight mode</Description>
        <Domain>COMMON</Domain>
        <Type>bool</Type>
        <PossibleValues override="true"/>
        <DefaultValue override="true">false</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="IS_BLUETOOTH_ENABLED">
        <Description>Enabled/Disabled Bluetooth</Description>
        <Domain>COMMON</Domain>
        <Type>bool</Type>
        <PossibleValues override="false">true;false</PossibleValues>
        <DefaultValue override="true">false</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="IS_DATA_ENABLED">
        <Description>Enabled/Disabled Data</Description>
        <Domain>COMMON</Domain>
        <Type>bool</Type>
        <PossibleValues override="false">true;false</PossibleValues>
        <DefaultValue override="true">false</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="IS_HPLMN_COVERAGE_AVAILABLE">
        <Description>iS Home Public Land Mobile Network Coverage available ?</Description>
        <Domain>COMMON</Domain>
        <Type>bool</Type>
        <PossibleValues override="false">true;false</PossibleValues>
        <DefaultValue override="true">false</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="DL_FILENAME">
        <Description>File to download from a server. ACS gets its value from BenchConfig using ftp_path key of SERVER
            equipments (WIFI_SERVER, LAB_SERVER...)
        </Description>
        <Domain>COMMON</Domain>
        <Type>str</Type>
        <PossibleValues override="false"/>
        <DefaultValue override="false"/>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="UL_FILENAME">
        <Description>File to upload on the server. This file shall be available on the device. ACS gets its value from
            DeviceCatalog, BenchConfig or CLI using key ftpPath
        </Description>
        <Domain>COMMON</Domain>
        <Type>file</Type>
        <PossibleValues override="false"/>
        <DefaultValue override="false"/>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="MUM_FILE">
        <Description>Multimedia file to play (audio, video, picture) - Ex : toto.mp3, tata.mp4, titi.jpg</Description>
        <Domain>COMMON</Domain>
        <Type>file</Type>
        <PossibleValues override="false"/>
        <DefaultValue override="false"/>
        <Blank override="true">false</Blank>
    </Parameter>
    <Parameter name="IS_SILENT_MODE_ENABLED">
        <Description>Enable/Disable silent mode</Description>
        <Domain>COMMON</Domain>
        <Type>bool</Type>
        <PossibleValues override="false">true;false</PossibleValues>
        <DefaultValue override="true">false</DefaultValue>
        <Blank override="false">false</Blank>
    </Parameter>
    <Parameter name="IPERF_PORT">
        <Description>IPERF port to be used. 5001 for TCP 5009 for UDP</Description>
        <Domain>COMMON</Domain>
        <Type>int</Type>
        <PossibleValues override="false">5001;5009</PossibleValues>
        <DefaultValue override="true">5001</DefaultValue>
        <Blank override="true">false</Blank>
    </Parameter>
    <Parameter name="IPERF_MODE">
        <Description>[Optional] Choose from single|concurrency|dual IPerf mode. Default is dual if unspecified:
            - Single will do a DUT client and equipment server IPerf transfer (If using AGILENT_E6621A IPerf server must
            be launched manually)
            - Dual will do for DL: a DUT server and equipment client IPerf transfer, and for UL: the same as single mode
            (same comment as above for AGILENT_E6621A)
            - Concurrency will do two IPerf transfer at the same time: DUT and equipment are both client and server.
        </Description>
        <Domain>COMMON</Domain>
        <Type>str</Type>
        <PossibleValues override="false">single;dual;concurrency</PossibleValues>
        <DefaultValue override="true">dual</DefaultValue>
        <Blank override="true">false</Blank>
    </Parameter>
    <Parameter name="TEST_SERVER">
        <Description>
            Server Configuration used for FTP, IPERF on test automation.
            Refers to a configuration on Bench_Config.
            Should contain at least these parameters:
            - IP (ip address of the equipment)
            - username (login used for the connection)
            - password (password used for the connection)
            Can contain:
            - IPV6 (prefix and ipv6 address of the equipment)
            - ftp_path (full path of home ftp directory)
        </Description>
        <Domain>COMMON</Domain>
        <Type>str</Type>
        <!-- Warning for later acs evolution, possible values to be checked-->
